version: "3.8"

services:
  django-web:
    build: .
    container_name: django-docker
    # command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media:/app/static/images
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=django-insecure-test-key
    #   - SQL_ENGINE=django.db.backends.postgresql
    #   - SQL_DATABASE=ecomm_db
    #   - SQL_USER=postgres
    #   - SQL_PASSWORD=root
    #   - SQL_HOST=127.0.0.1
    #   - SQL_PORT=5432

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=root
    #   - POSTGRES_DB=ecomm_db
  frontend-proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web
volumes:
  postgres_data:
